# Generated by Django 5.0.7 on 2024-07-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Prefeito', 'Prefeito'), ('Vereador', 'Vereador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('pesquisadora', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('idade', models.CharField(choices=[('16-25', '16 a 25 anos'), ('26-34', '26 a 34 anos'), ('35-55', '35 a 55 anos'), ('55+', 'Acima de 55 anos')], max_length=5)),
                ('votaria_brazao', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('rede_social', models.CharField(choices=[('FB', 'Facebook'), ('WA', 'WhatsApp'), ('IG', 'Instagram'), ('TW', 'Twitter'), ('YT', 'YouTube'), ('OT', 'Outros')], max_length=2)),
                ('prioridade_prefeito', models.CharField(max_length=100)),
                ('politico_mais_fez', models.CharField(max_length=100)),
                ('votaria_presidente', models.CharField(choices=[('LL', 'LULA'), ('BS', 'BOLSONARO')], max_length=2)),
                ('vereador_espontaneo_1', models.CharField(blank=True, max_length=100, null=True)),
                ('vereador_espontaneo_2', models.CharField(blank=True, max_length=100, null=True)),
                ('vereador_espontaneo_3', models.CharField(blank=True, max_length=100, null=True)),
                ('vereador_espontaneo_4', models.CharField(blank=True, max_length=100, null=True)),
                ('vereador_espontaneo_5', models.CharField(blank=True, max_length=100, null=True)),
                ('vereador_espontaneo_6', models.CharField(blank=True, max_length=100, null=True)),
                ('prefeito', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'Prefeito'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisas_prefeito', to='pesquisa.candidato')),
                ('vereador', models.ManyToManyField(limit_choices_to={'cargo': 'Vereador'}, related_name='pesquisas_vereador', to='pesquisa.candidato')),
                ('vereador_induzido', models.ManyToManyField(blank=True, limit_choices_to={'cargo': 'Vereador'}, related_name='pesquisas_vereador_induzido', to='pesquisa.candidato')),
            ],
        ),
    ]
