# Generated by Django 5.0.7 on 2024-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0003_alter_pesquisa_vereador_espontaneo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='vereador_induzido',
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='vereador_induzido',
            field=models.CharField(blank=True, help_text='Felipe Michel, Kaio Brazao,Carlos Caiado,Luiz Carlos,Ramos Filho,Não Sabe', max_length=1000),
        ),
    ]
