# Generated by Django 5.0.7 on 2024-07-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0004_remove_pesquisa_vereador_induzido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='vereador',
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='vereador_induzido',
            field=models.CharField(choices=[('FM', 'Felipe Michel'), ('KB', 'Kaio Brazao'), ('CC', 'Carlos Caiado'), ('LC', 'Luiz Carlos'), ('RC', 'Ramos Filho'), ('NS', 'Não Sabe')], max_length=2),
        ),
    ]
