# Generated by Django 5.0.7 on 2024-07-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0006_remove_pesquisa_prefeito_pesquisa_vereador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='cargo',
        ),
    ]
