# Generated by Django 5.0.7 on 2024-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0008_pesquisa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='bairro',
            field=models.CharField(choices=[('TP', 'Tropical'), ('ML', 'Monte Libano'), ('PT', 'Prata')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='cidade',
            field=models.CharField(choices=[('NI', 'Nova Iguaçu')], max_length=2),
        ),
    ]
