# Generated by Django 5.0.7 on 2024-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0009_alter_pesquisa_bairro_alter_pesquisa_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='vereador',
            field=models.CharField(choices=[('RODRIGO WILTON', 'Rodrigo Wilton'), ('HENRIQUE MUNIZ', 'Henrique Muniz'), ('FULANO', 'Fulano')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
